# scene
scene: gibson
scene_id: Dunmor
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: true

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
n_robots: 3
initial_pos: [[0,0,0],[0,0.5,0],[0.5,0,0]]
initial_orn: [[0,0,0],[0,0,0],[0,0,0]]
robots:
  -
    id: 0
    name: Locobot
    action_type: continuous
    action_normalize: true
    base_name: null
    scale: 1.0
    self_collision: false
    rendering_params: null
    controller_config:
      base:
        name: DifferentialDriveController
  -
    id: 1
    name: Locobot
    action_type: continuous
    action_normalize: true
    base_name: null
    scale: 1.0
    self_collision: false
    rendering_params: null
    controller_config:
      base:
        name: DifferentialDriveController
  -
    id: 2
    name: Locobot
    action_type: continuous
    action_normalize: true
    base_name: null
    scale: 1.0
    self_collision: false
    rendering_params: null
    controller_config:
      base:
        name: DifferentialDriveController


# task
task: semantic_mapping
task_obs_dim: 2

# reward
success_reward: 10.0
collision_reward_weight: -0.2

# discount factor
discount_factor: 0.99

# termination condition
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
output: [task_obs, rgb, depth]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 640
image_height: 480
vertical_fov: 45
camera_elevation_degree: -20
camera_height: 0.87
# depth
depth_low: 0.5
depth_high: 5
# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0



